---
- name: Ensure /etc/docker directory exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0755"
  tags: [user_setup, docker, logging]

- name: Configure Docker daemon with log rotation
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3",
          "compress": "true"
        }
      }
    mode: "0644"
  notify: "restart docker for logging"
  tags: [user_setup, docker, logging]

- name: Create logrotate configuration for Docker
  ansible.builtin.copy:
    dest: /etc/logrotate.d/docker-containers
    content: |
      /var/lib/docker/containers/*/*.log {
        rotate 7
        daily
        compress
        missingok
        delaycompress
        copytruncate
        size 10M
      }
    mode: "0644"
  tags: [user_setup, docker, logging]
