---
dependencies: []
galaxy_info:
  author: PumpFun
  description: Role to deploy Traefik as a reverse proxy.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
